### ISSUE TITLE
Upgrade for dotnet 6?

### ISSUE THREAD

**Issue by ghost** [olsh/dotnet-consolidate#15]
The current release requires dotnet 3.1 sdk to be installed as a pre-requiste into CI pipeline even when project targets net6.0 moniker.  Can major version be released?

**Comment by ITDancer13** [comment]
I've created a PR #19  for that :-)

**Comment by ITDancer13** [comment]
@olsh Thanks for merging, but I cannot see a release for that. Do you need to do that manually or went something wrong in the pipeline?

**Comment by olsh** [comment]
@ITDancer13 , yep, uploading on NuGet is a manual operation.
Probably we need to close https://github.com/olsh/dotnet-consolidate/issues/8 before pushing the update.

**Comment by ITDancer13** [comment]
Okay, I'll prepare a PR fot #8 first.

**Comment by Piedone** [comment]
First of all, thank you for this great tool!

Since https://github.com/olsh/dotnet-consolidate/pull/19 is merged, it would be great if this could be released.

I'm working on using `dotnet-consolidate` in a .NET build GHA workflow as a check (https://github.com/Lombiq/GitHub-Actions/issues/31) and this is blocked on the requirement of installing .NET Core 3.1 (it's only necessary for this, and I wouldn't want to add a variable into the build environment that may have unexpected consequences later on).

BTW if you want to automate releases, I recommend you check out this workflow and the corresponding actions: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/publish-nuget.yml You just add a tag to a branch (like "v1.2.3") or use any other event, and everything else happens automatically after that: Source Link integration, nuspec generation if necessary, .NET restore and build, NuGet pack and publish (to a configurable feed, can also be Cloudsmith, for example), create release on GitHub.

**Comment by olsh** [comment]
Hi guys,

I've just pushed the updated version to NuGet.
Thank you for the help.

> BTW if you want to automate releases

They are already automated. I use AppVeyor for this. The only action I should perform manually is hitting the `Deploy` button.

**Comment by Piedone** [comment]
Great, thank you!

Didn't you forget to add a release on GitHub?

**Comment by olsh** [comment]
@Piedone yep, thank you for the reminder.
